### ISSUE TITLE
Settings select "Multiple authors" Display error "Unable to locate the file:blog_users.php"

### ISSUE THREAD

**Issue by casaca** [daylightstudio/FUEL-CMS-Blog-Module#21]
Settings select "Multiple authors" Display error "Unable to locate the file:blog_users.php"

**Comment by casaca** [comment]
Looking forward to respond to this issues, My English is not good, and I pay attention to the FUEL-CMS time is not long, Don't know too many other things.

**Comment by daylightstudio** [comment]
What version of FUEL are you running (master branch or develop branch). The current version of the blog module is geared to run with develop branch at the moment which uses CI 3.0.

**Comment by casaca** [comment]
Oh, I'm sorry about the versions.
PHP version: V5.4
CI version:   CI 2.2.1
FUEL-CMS:  master branch
FUEL-CMS-Blog-Module: master branch

**Comment by daylightstudio** [comment]
I've pushed a fix for this issue.
