### ISSUE TITLE
errors after installing the blog module on Fuelcms 1.4

### ISSUE THREAD

**Issue by BartVertongen** [daylightstudio/FUEL-CMS-Blog-Module#27]
Severity: Runtime Notice

Message: Declaration of Fuel_blog::model() should be compatible with & Fuel_advanced_module::model($model = NULL)
I did it manually and with the install script and I had the same problem.
I am a new user of fuel it would take me too long to find the probem myself

**Comment by daylightstudio** [comment]
This looks symptomatic of a FUEL version issue. The Blog module requires FUEL 1.4. To check the version of FUEL, go to fuel/modules/fuel/config/fuel_constants.php.

http://docs.getfuelcms.com/installation/installing

**Comment by BartVertongen** [comment]
I checked it it says 1.4

**Comment by daylightstudio** [comment]
The blog module should be updated as well. The develop version had that fix in it for a while and was just merged over this week actually.

**Comment by BartVertongen** [comment]
I downloaded the module using zip yesterday.
Would it be correct if I used git?

**Comment by daylightstudio** [comment]
Does your fuel/modules/blog/libraries/Fuel_blog.php file have this change:
https://github.com/daylightstudio/FUEL-CMS-Blog-Module/commit/0c50d55f9445989a52e0ffadcffc2b3d2dd95ea9

**Comment by BartVertongen** [comment]
I did not use git , I downloaded the zip.

biut in the file I see
/**
 * The Main Library class used in the blog
 *
 * @package		FUEL BLOG
 * @subpackage	Libraries
 * @category	Libraries
 * @author		David McReynolds @ Daylight Studio
 * @link		http://docs.getfuelcms.com/modules/blog/fuel_blog
 */

class Fuel_blog extends Fuel_advanced_module {
	
	protected $_settings = NULL;
	protected $_current_post = NULL;

	/**
	 * Constructor
	 *
	 * The constructor can be passed an array of config values
	 */

**Comment by BartVertongen** [comment]
so it extends fuel_advanced module

**Comment by BartVertongen** [comment]
ok I understand now yes the ampersand is gone

**Comment by daylightstudio** [comment]
Are you still seeing that error?

**Comment by BartVertongen** [comment]
If I put the & back it works

**Comment by BartVertongen** [comment]
but my fuel installation is not from this week but older, my blogs module is from this week

**Comment by daylightstudio** [comment]
Does your Fuel_advance_module class include the `&` in front of the model method? It shouldn't.

**Comment by BartVertongen** [comment]
No not in the class fileof  Fuel_advance_module
 but in the Fuel_blog library I have to add it to make it work

**Comment by daylightstudio** [comment]
I see. The FUEL develop branch has that fix but the master branch does not.

**Comment by BartVertongen** [comment]
yes the model function in the class has it, has the ampersand.
before I just looked in front of the class declaration (the start class ...)
so if I remove it there it would be ok with the new blog module

**Comment by BartVertongen** [comment]
ok thanks
